#!/usr/bin/env bash
# build-sw.sh — Generate a static sw.js snapshot with a content-hashed asset manifest
#
# Runtime now registers root/sw.ssjs, which computes the same manifest
# dynamically so the installed PWA stays evergreen without this script.
# This helper remains available when you want a static sw.js snapshot.
#
# Usage: ./build-sw.sh
#
set -euo pipefail
cd "$(dirname "$0")/root"

# ─── Collect all local assets to cache ──────────────────────
# JS, CSS, lib, images, fonts, HTML fragments
ASSETS=()
while IFS= read -r f; do
    ASSETS+=("./${f}")
done < <(
    find -L js css lib images -type f \( \
        -name '*.js' -o -name '*.css' -o -name '*.png' \
        -o -name '*.jpg' -o -name '*.gif' -o -name '*.ico' \
        -o -name '*.svg' -o -name '*.woff2' -o -name '*.woff' \
        -o -name '*.ttf' -o -name '*.eot' \
    \) 2>/dev/null | sort
)
# terminal-iframe.html
ASSETS+=("./terminal-iframe.html")

# ─── Build revision map: path → md5 hash ───────────────────
MANIFEST_ENTRIES=""
COMBINED_HASH=""
for asset in "${ASSETS[@]}"; do
    # Strip leading ./ for the key
    file="${asset#./}"
    if [[ ! -f "$file" ]]; then continue; fi
    hash=$(md5sum "$file" | cut -c1-12)
    COMBINED_HASH+="$hash"
    MANIFEST_ENTRIES+="    '${asset}': '${hash}',"$'\n'
done

# Overall revision = hash of all individual hashes
REVISION=$(printf '%s' "$COMBINED_HASH" | md5sum | cut -c1-12)

# CDN assets (stable, versioned URLs — hash is the version string)
CDN_ASSETS=(
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
)
for cdn in "${CDN_ASSETS[@]}"; do
    MANIFEST_ENTRIES+="    '${cdn}': 'cdn-pinned',"$'\n'
done

echo "Revision: $REVISION (${#ASSETS[@]} local assets)"

# ─── Generate sw.js ─────────────────────────────────────────
cat > sw.js << SWEOF
// AUTO-GENERATED by build-sw.sh — do not edit manually
// Revision: ${REVISION}
// Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')

var CACHE_NAME = 'futureland-${REVISION}';

// Asset manifest: path → content hash
// When any hash changes, CACHE_NAME changes, triggering full refresh.
var ASSET_MANIFEST = {
${MANIFEST_ENTRIES}};

var PRECACHE_URLS = Object.keys(ASSET_MANIFEST);

// Also cache the shell HTML (served dynamically by .xjs)
var SHELL_URLS = [
    './',
    './?page=000-home.xjs'
];

// ── Install: precache all hashed assets ─────────────────────
self.addEventListener('install', function (event) {
    event.waitUntil(
        caches.open(CACHE_NAME).then(function (cache) {
            // Cache static assets (these are fingerprinted by manifest)
            return cache.addAll(PRECACHE_URLS);
        }).then(function () {
            // Also try to cache the HTML shell (may need auth, ok to fail)
            return caches.open(CACHE_NAME).then(function (cache) {
                return Promise.all(SHELL_URLS.map(function (url) {
                    return cache.add(url).catch(function () {
                        console.log('[SW] Shell URL skipped:', url);
                    });
                }));
            });
        }).then(function () {
            // Activate immediately — don't wait for tabs to close
            return self.skipWaiting();
        })
    );
});

// ── Activate: purge all old caches ──────────────────────────
self.addEventListener('activate', function (event) {
    event.waitUntil(
        caches.keys().then(function (names) {
            return Promise.all(
                names.filter(function (n) { return n !== CACHE_NAME; })
                     .map(function (n) {
                         console.log('[SW] Purging old cache:', n);
                         return caches.delete(n);
                     })
            );
        }).then(function () {
            // Take control of all open tabs immediately
            return self.clients.claim();
        })
    );
});

// ── Fetch strategy ──────────────────────────────────────────
//  API / SSE / POST → network only (never cache)
//  Manifest assets  → cache-first (guaranteed fresh by content hash)
//  HTML pages       → network-first, cache fallback
//  Unknown assets   → network-first, opportunistic cache
self.addEventListener('fetch', function (event) {
    var url = new URL(event.request.url);

    // Never cache non-GET, API calls, SSE streams, WebSockets
    if (event.request.method !== 'GET') return;
    if (url.pathname.indexOf('/api/') !== -1) return;
    if (url.pathname.indexOf('/events/') !== -1) return;
    if (url.pathname.indexOf('/ws') !== -1) return;

    var requestUrl = event.request.url;
    // Strip query strings for manifest lookup (our ?_v= timestamps)
    var bareUrl = requestUrl.split('?')[0];

    // Check if this URL (with or without query string) is in our manifest
    var isManifested = false;
    var keys = Object.keys(ASSET_MANIFEST);
    for (var i = 0; i < keys.length; i++) {
        // Resolve the manifest key to absolute URL for comparison
        var abs = new URL(keys[i], self.location.href).href;
        if (abs === bareUrl || abs === requestUrl) {
            isManifested = true;
            break;
        }
    }

    if (isManifested) {
        // Cache-first for manifested assets — they're content-hashed,
        // so if CACHE_NAME changed, old cache is already purged.
        event.respondWith(
            caches.match(event.request).then(function (cached) {
                if (cached) return cached;
                // Also try without query string
                return caches.match(bareUrl).then(function (cached2) {
                    if (cached2) return cached2;
                    return fetch(event.request).then(function (response) {
                        if (response && response.status === 200) {
                            var clone = response.clone();
                            caches.open(CACHE_NAME).then(function (c) {
                                c.put(event.request, clone);
                            });
                        }
                        return response;
                    });
                });
            })
        );
        return;
    }

    // HTML / page requests: network-first, fall back to cache
    if (event.request.headers.get('Accept') &&
        event.request.headers.get('Accept').indexOf('text/html') !== -1) {
        event.respondWith(
            fetch(event.request).then(function (response) {
                if (response && response.status === 200) {
                    var clone = response.clone();
                    caches.open(CACHE_NAME).then(function (c) {
                        c.put(event.request, clone);
                    });
                }
                return response;
            }).catch(function () {
                return caches.match(event.request);
            })
        );
        return;
    }

    // Everything else: network-first, opportunistic cache
    event.respondWith(
        fetch(event.request).then(function (response) {
            if (response && response.status === 200 &&
                url.origin === self.location.origin) {
                var clone = response.clone();
                caches.open(CACHE_NAME).then(function (c) {
                    c.put(event.request, clone);
                });
            }
            return response;
        }).catch(function () {
            return caches.match(event.request);
        })
    );
});

// ── Message handler: allow page to trigger skipWaiting ──────
self.addEventListener('message', function (event) {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
SWEOF

echo "Generated sw.js with CACHE_NAME='futureland-${REVISION}'"
