// AUTO-GENERATED by build-sw.sh — do not edit manually
// Revision: 6065e4c41db2
// Generated: 2026-03-29T06:10:51Z

var CACHE_NAME = 'futureland-6065e4c41db2';

// Asset manifest: path → content hash
// When any hash changes, CACHE_NAME changes, triggering full refresh.
var ASSET_MANIFEST = {
    './css/ansi-editor-modal.css': '75562122c2ce',
    './css/checkbox.css': '9a769a8c6fea',
    './css/custom.css': 'd7f6aba14fbb',
    './css/navbar-fixed-top.css': '76063e564adb',
    './css/news.css': 'ee3104c8a5c0',
    './css/offcanvas.css': '34e9f68baab2',
    './css/spa.css': 'c0198e816dca',
    './css/style.css': '24123dc188e0',
    './css/theme-cga.css': '8206b1a4ed7d',
    './images/ajax-loader-small.gif': '4889784689c1',
    './images/apple-touch-icon.png': 'c6dcf68e1cc8',
    './images/cp437-ibm-vga8.png': '51ef7afc1b39',
    './images/favicon.ico': 'b40c4ceab3c9',
    './images/icon-192.png': '5978edf19b6c',
    './images/icon-512.png': '2aabe03ddac1',
    './images/icon-maskable-192.png': 'dc3a604cf671',
    './images/icon-maskable-512.png': 'ba6e0b71bb52',
    './images/vektrax3.png': '78de0d4726ed',
    './images/vektrax_banner.png': '63f8d0f6c88b',
    './js/ansi-editor-forum.js': '0eb96904995e',
    './js/ansi-editor-modal.js': 'c19afde7c93e',
    './js/avatars.js': '57f26a24eb71',
    './js/bin-avatar-upload.js': '661097ea0d4a',
    './js/bin-icons.js': '3d2a778dbdf6',
    './js/cache.js': '5e9b94dc01f1',
    './js/chat.js': '7f3384fde385',
    './js/common.js': '65dfd082e60c',
    './js/flweb.js': 'ade37d162545',
    './js/forum.js': '452f8e973f77',
    './js/games.js': '66123d83f5ca',
    './js/graphics-converter.js': 'b67a4f361817',
    './js/jquery.min.js': 'f03e5a3bf534',
    './js/mobile-input.js': '94055e40eeda',
    './js/mqtt.js': 'dd55f79ac44a',
    './js/news.js': '88ab9dc79371',
    './js/nodespy.js': 'd53f70ccbb1d',
    './js/offcanvas.js': '0c32e71e9925',
    './js/oneliners.js': '1fbb8697a068',
    './js/radio.js': '386699070fd0',
    './js/spa.js': '0750b2c8c083',
    './js/terminal.js': 'de38761ffaac',
    './js/utf8_cp437.js': '561b85883d26',
    './js/validator.js': '50571401d3ae',
    './js/visualizer.js': 'c1cd52dc86f9',
    './js/webmonitor.js': '3fbf5c4f91a5',
    './js/xjs-forum.js': 'c6c3e2facc82',
    './lib/butterchurn.min.js': 'f6d5c5fc8d67',
    './lib/butterchurnPresets.min.js': '054173b5c718',
    './terminal-iframe.html': '9d133683dbcf',
    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css': 'cdn-pinned',
    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js': 'cdn-pinned',
};

var PRECACHE_URLS = Object.keys(ASSET_MANIFEST);

// Also cache the shell HTML (served dynamically by .xjs)
var SHELL_URLS = [
    './',
    './?page=000-home.xjs'
];

// ── Install: precache all hashed assets ─────────────────────
self.addEventListener('install', function (event) {
    event.waitUntil(
        caches.open(CACHE_NAME).then(function (cache) {
            // Cache static assets (these are fingerprinted by manifest)
            return cache.addAll(PRECACHE_URLS);
        }).then(function () {
            // Also try to cache the HTML shell (may need auth, ok to fail)
            return caches.open(CACHE_NAME).then(function (cache) {
                return Promise.all(SHELL_URLS.map(function (url) {
                    return cache.add(url).catch(function () {
                        console.log('[SW] Shell URL skipped:', url);
                    });
                }));
            });
        }).then(function () {
            // Activate immediately — don't wait for tabs to close
            return self.skipWaiting();
        })
    );
});

// ── Activate: purge all old caches ──────────────────────────
self.addEventListener('activate', function (event) {
    event.waitUntil(
        caches.keys().then(function (names) {
            return Promise.all(
                names.filter(function (n) { return n !== CACHE_NAME; })
                     .map(function (n) {
                         console.log('[SW] Purging old cache:', n);
                         return caches.delete(n);
                     })
            );
        }).then(function () {
            // Take control of all open tabs immediately
            return self.clients.claim();
        })
    );
});

// ── Fetch strategy ──────────────────────────────────────────
//  API / SSE / POST → network only (never cache)
//  Manifest assets  → cache-first (guaranteed fresh by content hash)
//  HTML pages       → network-first, cache fallback
//  Unknown assets   → network-first, opportunistic cache
self.addEventListener('fetch', function (event) {
    var url = new URL(event.request.url);

    // Never cache non-GET, API calls, SSE streams, WebSockets
    if (event.request.method !== 'GET') return;
    if (url.pathname.indexOf('/api/') !== -1) return;
    if (url.pathname.indexOf('/events/') !== -1) return;
    if (url.pathname.indexOf('/ws') !== -1) return;

    var requestUrl = event.request.url;
    // Strip query strings for manifest lookup (our ?_v= timestamps)
    var bareUrl = requestUrl.split('?')[0];

    // Check if this URL (with or without query string) is in our manifest
    var isManifested = false;
    var keys = Object.keys(ASSET_MANIFEST);
    for (var i = 0; i < keys.length; i++) {
        // Resolve the manifest key to absolute URL for comparison
        var abs = new URL(keys[i], self.location.href).href;
        if (abs === bareUrl || abs === requestUrl) {
            isManifested = true;
            break;
        }
    }

    if (isManifested) {
        // Cache-first for manifested assets — they're content-hashed,
        // so if CACHE_NAME changed, old cache is already purged.
        event.respondWith(
            caches.match(event.request).then(function (cached) {
                if (cached) return cached;
                // Also try without query string
                return caches.match(bareUrl).then(function (cached2) {
                    if (cached2) return cached2;
                    return fetch(event.request).then(function (response) {
                        if (response && response.status === 200) {
                            var clone = response.clone();
                            caches.open(CACHE_NAME).then(function (c) {
                                c.put(event.request, clone);
                            });
                        }
                        return response;
                    });
                });
            })
        );
        return;
    }

    // HTML / page requests: network-first, fall back to cache
    if (event.request.headers.get('Accept') &&
        event.request.headers.get('Accept').indexOf('text/html') !== -1) {
        event.respondWith(
            fetch(event.request).then(function (response) {
                if (response && response.status === 200) {
                    var clone = response.clone();
                    caches.open(CACHE_NAME).then(function (c) {
                        c.put(event.request, clone);
                    });
                }
                return response;
            }).catch(function () {
                return caches.match(event.request);
            })
        );
        return;
    }

    // Everything else: network-first, opportunistic cache
    event.respondWith(
        fetch(event.request).then(function (response) {
            if (response && response.status === 200 &&
                url.origin === self.location.origin) {
                var clone = response.clone();
                caches.open(CACHE_NAME).then(function (c) {
                    c.put(event.request, clone);
                });
            }
            return response;
        }).catch(function () {
            return caches.match(event.request);
        })
    );
});

// ── Message handler: allow page to trigger skipWaiting ──────
self.addEventListener('message', function (event) {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
